In [3]:
# pip install xarray

Collecting xarray
  Downloading xarray-0.18.2-py3-none-any.whl (807 kB)
Requirement already satisfied: setuptools>=40.4 in c:\users\hadunka2\.conda\envs\ace592\lib\site-packages (from xarray) (49.6.0.post20210108)
Requirement already satisfied: numpy>=1.17 in c:\users\hadunka2\.conda\envs\ace592\lib\site-packages (from xarray) (1.21.0)
Requirement already satisfied: pandas>=1.0 in c:\users\hadunka2\.conda\envs\ace592\lib\site-packages (from xarray) (1.1.3)
Requirement already satisfied: pytz>=2017.2 in c:\users\hadunka2\.conda\envs\ace592\lib\site-packages (from pandas>=1.0->xarray) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\hadunka2\.conda\envs\ace592\lib\site-packages (from pandas>=1.0->xarray) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\users\hadunka2\.conda\envs\ace592\lib\site-packages (from python-dateutil>=2.7.3->pandas>=1.0->xarray) (1.16.0)
Installing collected packages: xarray
Successfully installed xarray-0.18.2
Note: you may need to restart the kernel to use updated packages.

In [4]:
import os, glob
import numpy as np
import xarray as xr
import pandas as pd
from shapely.geometry import Point
from pyproj import CRS
import geopandas as gpd
import rasterio

In [5]:
maize_pts = pd.read_csv(r'C:\Users\hadunka2\Box\Research proposals\geocodes_final_2019.csv')
maize_pts.head()

       HHID  new_latitude  new_longitude
0  10117002     -13.51900       28.94150
1  10117003     -13.52473       28.93653
2  10117004     -13.53560       28.91180
3  10117005     -13.52707       28.93000
4  10117006     -13.56519       28.90073

In [6]:
# lst_tif_dir =r'C:\Users\gv4\Box\2. Research\Daily Temperature Coding\FoodMarkets-main (1)\FoodMarkets-main\Data_tiff'
lst_tif_dir = r'C:\Users\hadunka2\Box\Research proposals\Datatiff'

In [7]:
def extract_value_points(in_dir, gps_df, x_col, y_col):
    
    coords = [(x,y) for x, y in zip(gps_df[x_col], gps_df[y_col])]
    
    files = np.array(sorted(os.listdir(in_dir)))
    tifs = pd.Series(files).str.endswith('.tif')
    files = files[tifs]
    
    for filename in files:
        print(filename)
        #extract date from filename (will convert to y-m-d form later)
        name = filename[filename.find('A')+1 : filename.find('.006')]
        src = rasterio.open(in_dir + "/"+filename)
        
        #sample values from list of coordinates
        values = [x[0] for x in src.sample(coords)]
        #set all 0's to nan
        values = [np.nan if x==0 else x for x in values]
        #convert values from kelvin to celsius
        values = [round((0.02 * x - 273.15),2) for x in values]
        gps_df['LST ' + str(name)] = values

    return gps_df

In [8]:
df = extract_value_points(lst_tif_dir, maize_pts, 'new_longitude', 'new_latitude')

MYD11C1.A2002185.006.2015168205342.tif
MYD11C1.A2002186.006.2015146153828.tif
MYD11C1.A2002187.006.2015146153817.tif
MYD11C1.A2002188.006.2015168205344.tif
MYD11C1.A2002189.006.2015146153815.tif
MYD11C1.A2002190.006.2015146153820.tif
MYD11C1.A2002191.006.2015146153820.tif
MYD11C1.A2002192.006.2015168205314.tif
MYD11C1.A2002193.006.2015146153820.tif
MYD11C1.A2002194.006.2015149015641.tif
MYD11C1.A2002195.006.2015146153819.tif
MYD11C1.A2002196.006.2015149015730.tif
MYD11C1.A2002197.006.2015149015630.tif
MYD11C1.A2002198.006.2015146153840.tif
MYD11C1.A2002199.006.2015146154059.tif
MYD11C1.A2002200.006.2015146154109.tif
MYD11C1.A2002201.006.2015149015655.tif
MYD11C1.A2002202.006.2015146153945.tif
MYD11C1.A2002203.006.2015149015701.tif
MYD11C1.A2002204.006.2015149015730.tif
MYD11C1.A2002205.006.2015146154133.tif
MYD11C1.A2002206.006.2015146154415.tif
MYD11C1.A2002207.006.2015149015731.tif
MYD11C1.A2002208.006.2015149015724.tif
MYD11C1.A2002209.006.2015149015854.tif
MYD11C1.A2002210.006.2015146154440.tif
MYD11C1.A2002220.006.2015149015949.tif
MYD11C1.A2002221.006.2015148214313.tif
MYD11C1.A2002222.006.2015149015940.tif
MYD11C1.A2002223.006.2015149015912.tif
MYD11C1.A2002224.006.2015149020013.tif
MYD11C1.A2002225.006.2015149020019.tif
MYD11C1.A2002226.006.2015150081416.tif
MYD11C1.A2002227.006.2015150081358.tif
MYD11C1.A2002228.006.2015150081406.tif
MYD11C1.A2002229.006.2015150081327.tif
MYD11C1.A2002230.006.2015150081300.tif
MYD11C1.A2002231.006.2015150081351.tif
MYD11C1.A2002232.006.2015150081354.tif
MYD11C1.A2002233.006.2015150081351.tif
MYD11C1.A2002234.006.2015150081519.tif
MYD11C1.A2002235.006.2015149113133.tif
MYD11C1.A2002236.006.2015149130806.tif
MYD11C1.A2002237.006.2015150081538.tif
MYD11C1.A2002238.006.2015149150908.tif
MYD11C1.A2002239.006.2015149154249.tif
MYD11C1.A2002240.006.2015150081548.tif
MYD11C1.A2002241.006.2015150081556.tif
MYD11C1.A2002242.006.2015149192100.tif
MYD11C1.A2002243.006.2015150081613.tif
MYD11C1.A2002244.006.2015150081615.tif
MYD11C1.A2002245.006.2015149221402.tif
MYD11C1.A2002246.006.2015150081613.tif
MYD11C1.A2002247.006.2015150002357.tif
MYD11C1.A2002248.006.2015150020222.tif
MYD11C1.A2002249.006.2015150081633.tif
MYD11C1.A2002250.006.2015150082021.tif
MYD11C1.A2002251.006.2015150042748.tif
MYD11C1.A2002252.006.2015150082017.tif
MYD11C1.A2002253.006.2015150060352.tif
MYD11C1.A2002254.006.2015150072653.tif
MYD11C1.A2002255.006.2015150082030.tif
MYD11C1.A2002257.006.2015161123214.tif
MYD11C1.A2002258.006.2015161123224.tif
MYD11C1.A2002259.006.2015152183120.tif
MYD11C1.A2002260.006.2015161123200.tif
MYD11C1.A2002261.006.2015152202514.tif
MYD11C1.A2002262.006.2015161123210.tif
MYD11C1.A2002263.006.2015161123214.tif
MYD11C1.A2002264.006.2015152230416.tif
MYD11C1.A2002265.006.2015161123225.tif
MYD11C1.A2002266.006.2015161123158.tif
MYD11C1.A2002267.006.2015161123214.tif
MYD11C1.A2002268.006.2015161123340.tif
MYD11C1.A2002269.006.2015161123337.tif
MYD11C1.A2002270.006.2015160175326.tif
MYD11C1.A2002271.006.2015160175250.tif
MYD11C1.A2002272.006.2015160200436.tif
MYD11C1.A2002273.006.2015161123357.tif
MYD11C1.A2002274.006.2015161123355.tif
MYD11C1.A2002275.006.2015161123358.tif
MYD11C1.A2002276.006.2015161123353.tif
MYD11C1.A2002277.006.2015161002503.tif
MYD11C1.A2002278.006.2015161014720.tif
MYD11C1.A2002279.006.2015161123417.tif
MYD11C1.A2002280.006.2015161123404.tif
MYD11C1.A2002281.006.2015161123516.tif
MYD11C1.A2002282.006.2015161123517.tif
MYD11C1.A2002283.006.2015161063206.tif
MYD11C1.A2002284.006.2015161080645.tif
MYD11C1.A2002285.006.2015161123527.tif
MYD11C1.A2002286.006.2015161102308.tif
MYD11C1.A2002287.006.2015161123527.tif
MYD11C1.A2002288.006.2015161123529.tif
MYD11C1.A2002289.006.2015163145028.tif
MYD11C1.A2002290.006.2015163145030.tif
MYD11C1.A2002291.006.2015161150900.tif
MYD11C1.A2002292.006.2015163145028.tif
MYD11C1.A2002293.006.2015161180726.tif
MYD11C1.A2002294.006.2015163145032.tif
MYD11C1.A2002295.006.2015163145037.tif
MYD11C1.A2002296.006.2015161233600.tif
MYD11C1.A2002297.006.2015163145041.tif
MYD11C1.A2002298.006.2015163145047.tif
MYD11C1.A2002299.006.2015163145206.tif
MYD11C1.A2002300.006.2015162052314.tif
MYD11C1.A2002301.006.2015163145205.tif
MYD11C1.A2002302.006.2015162074138.tif
MYD11C1.A2002303.006.2015162085310.tif
MYD11C1.A2002304.006.2015163145200.tif
MYD11C1.A2002305.006.2015163145158.tif
MYD11C1.A2002306.006.2015163145159.tif
MYD11C1.A2002307.006.2015162131325.tif
MYD11C1.A2002308.006.2015163145204.tif
MYD11C1.A2002309.006.2015162191546.tif
MYD11C1.A2002310.006.2015162192300.tif
MYD11C1.A2002311.006.2015163145211.tif
MYD11C1.A2002312.006.2015162205623.tif
MYD11C1.A2002313.006.2015163145212.tif
MYD11C1.A2002314.006.2015163145325.tif
MYD11C1.A2002315.006.2015163145325.tif
MYD11C1.A2002316.006.2015163000537.tif
MYD11C1.A2002317.006.2015163145322.tif
MYD11C1.A2002318.006.2015163013812.tif
MYD11C1.A2002319.006.2015163145322.tif
MYD11C1.A2002320.006.2015163145337.tif
MYD11C1.A2002321.006.2015166183230.tif
MYD11C1.A2002322.006.2015166183313.tif
MYD11C1.A2002323.006.2015163170807.tif
MYD11C1.A2002324.006.2015166183229.tif
MYD11C1.A2002325.006.2015163182333.tif
MYD11C1.A2002326.006.2015166183300.tif
MYD11C1.A2002327.006.2015166183300.tif
MYD11C1.A2002328.006.2015166183259.tif
MYD11C1.A2002329.006.2015166183230.tif
MYD11C1.A2002330.006.2015166183315.tif
MYD11C1.A2002331.006.2015164003103.tif
MYD11C1.A2002332.006.2015166183400.tif
MYD11C1.A2002333.006.2015166183403.tif
MYD11C1.A2002334.006.2015164030753.tif
MYD11C1.A2002335.006.2015166183435.tif

In [10]:
df

,HHID,new_latitude,new_longitude,LST 2002185,LST 2002186,LST 2002187,LST 2002188,LST 2002189,LST 2002190,LST 2002191,...,LST 2002326,LST 2002327,LST 2002328,LST 2002329,LST 2002330,LST 2002331,LST 2002332,LST 2002333,LST 2002334,LST 2002335
0,10117002,-13.51900,28.94150,27.09,29.91,29.73,29.27,23.61,29.27,28.37,...,38.21,NaN,NaN,NaN,NaN,NaN,NaN,34.59,NaN,34.97
1,10117003,-13.52473,28.93653,27.09,29.91,29.73,29.27,23.61,29.27,28.37,...,38.21,NaN,NaN,NaN,NaN,NaN,NaN,34.59,NaN,34.97
2,10117004,-13.53560,28.91180,27.09,29.91,29.73,29.27,23.61,29.27,28.37,...,38.21,NaN,NaN,NaN,NaN,NaN,NaN,34.59,NaN,34.97
3,10117005,-13.52707,28.93000,27.09,29.91,29.73,29.27,23.61,29.27,28.37,...,38.21,NaN,NaN,NaN,NaN,NaN,NaN,34.59,NaN,34.97
4,10117006,-13.56519,28.90073,26.55,29.61,29.01,28.77,25.91,28.65,29.11,...,36.11,NaN,36.15,NaN,NaN,NaN,NaN,36.81,NaN,35.69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744,60222016,-16.24963,26.72298,31.75,34.77,35.47,32.63,37.25,NaN,38.57,...,53.27,NaN,NaN,NaN,NaN,51.03,43.77,49.05,NaN,42.13
745,60222017,-16.24880,26.70430,31.75,34.77,35.47,32.63,37.25,NaN,38.57,...,53.27,NaN,NaN,NaN,NaN,51.03,43.77,49.05,NaN,42.13
746,60222018,-16.23173,26.67156,31.75,34.45,35.53,33.19,37.41,NaN,38.63,...,53.41,NaN,NaN,NaN,NaN,50.39,37.73,56.31,NaN,43.29
747,60222019,-16.24870,26.69130,31.75,34.45,35.53,33.19,37.41,NaN,38.63,...,53.41,NaN,NaN,NaN,NaN,50.39,37.73,56.31,NaN,43.29
748,60222020,-16.25610,26.70170,32.61,35.65,35.97,32.61,37.35,NaN,38.57,...,54.67,NaN,NaN,NaN,NaN,50.33,42.79,51.61,NaN,53.21

In [11]:
df.to_csv(r'C:\Users\hadunka2\Box\Research proposals\Final_temp.csv')